export default function ResultDisplay({ text, annotatedImage }) {
  const copyToClipboard = () => {
    navigator.clipboard.writeText(text)
      .then(() => alert("✅ Text copied to clipboard!"))
      .catch(() => alert("❌ Failed to copy"))
  }

  const downloadAsText = () => {
    const element = document.createElement("a")
    const file = new Blob([text], { type: "text/plain" })
    element.href = URL.createObjectURL(file)
    element.download = `braille-output-${new Date().toISOString().slice(0, 10)}.txt`
    document.body.appendChild(element)
    element.click()
    document.body.removeChild(element)
  }

  const downloadAsMarkdown = () => {
    const markdown = `# BrailleVision Output

**Date:** ${new Date().toLocaleString()}

## Decoded Text

${text}

---

**Stats:**
- Characters: ${text.length}
- Words: ${text.trim().split(/\s+/).length}

*Generated by BrailleVision — Real-Time Braille to English Converter*
`
    const element = document.createElement("a")
    const file = new Blob([markdown], { type: "text/markdown" })
    element.href = URL.createObjectURL(file)
    element.download = `braille-output-${new Date().toISOString().slice(0, 10)}.md`
    document.body.appendChild(element)
    element.click()
    document.body.removeChild(element)
  }

  return (
    <div className="result-display">
      <h2>📖 Decoded Text</h2>
      {annotatedImage && (
        <div className="result-visual">
          <h3>Model Output</h3>
          <img src={annotatedImage} alt="Annotated Braille output" />
        </div>
      )}
      <div className="result-text">
        {text || "Decoded text will appear here..."}
      </div>
      <div className="result-info">
        <p>Characters: {text.length}</p>
        <p>Words: {text.trim().split(/\s+/).length}</p>
      </div>
      
      <div className="output-actions">
        <button onClick={copyToClipboard} className="action-btn copy-btn">
          📋 Copy Text
        </button>
        <button onClick={downloadAsText} className="action-btn download-btn">
          💾 Download .TXT
        </button>
        <button onClick={downloadAsMarkdown} className="action-btn markdown-btn">
          📝 Download .MD
        </button>
      </div>
    </div>
  )
}

const styles = `
.result-display {
  display: flex;
  flex-direction: column;
  gap: 15px;
}

.result-display h2 {
  font-size: 1.3rem;
  color: #1e40af;
  margin-bottom: 10px;
}

.result-display.empty {
  justify-content: center;
  align-items: center;
  min-height: 150px;
  color: #999;
}

.result-visual {
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.result-visual h3 {
  font-size: 1rem;
  color: #0f172a;
}

.result-visual img {
  width: 100%;
  border-radius: 12px;
  border: 1px solid #dbeafe;
  box-shadow: 0 10px 25px rgba(15, 23, 42, 0.08);
}

.result-text {
  background-color: #f0f9ff;
  border: 2px solid #dbeafe;
  border-radius: 8px;
  padding: 15px;
  font-size: 1.1rem;
  line-height: 1.6;
  font-family: 'Courier New', monospace;
  word-break: break-all;
  min-height: 100px;
  display: flex;
  align-items: center;
}

.result-info {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 10px;
  padding: 10px 0;
  font-size: 0.9rem;
  color: #666;
}

.output-actions {
  display: grid;
  grid-template-columns: 1fr 1fr 1fr;
  gap: 10px;
  padding-top: 10px;
  border-top: 2px solid #f0f0f0;
}

.action-btn {
  padding: 10px 15px;
  border: none;
  border-radius: 6px;
  cursor: pointer;
  font-weight: bold;
  font-size: 0.95rem;
  transition: all 0.3s ease;
  color: white;
}

.copy-btn {
  background-color: #06b6d4;
}

.copy-btn:hover {
  background-color: #0891b2;
  transform: translateY(-2px);
  box-shadow: 0 4px 8px rgba(6, 182, 212, 0.3);
}

.download-btn {
  background-color: #8b5cf6;
}

.download-btn:hover {
  background-color: #7c3aed;
  transform: translateY(-2px);
  box-shadow: 0 4px 8px rgba(139, 92, 246, 0.3);
}

.markdown-btn {
  background-color: #ec4899;
}

.markdown-btn:hover {
  background-color: #db2777;
  transform: translateY(-2px);
  box-shadow: 0 4px 8px rgba(236, 72, 153, 0.3);
}

@media (max-width: 768px) {
  .output-actions {
    grid-template-columns: 1fr;
  }
}
`

if (typeof document !== 'undefined') {
  const styleSheet = document.createElement("style")
  styleSheet.textContent = styles
  document.head.appendChild(styleSheet)
}
