# -*- coding: utf-8 -*-
"""BrailleVision_Train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19ctCOOAjWXn6Y10T4BlH43lqK-EBt0zJ

# 🚀 BrailleVision: Object Detection Model Training

## 1. Environment Setup and Dependencies
"""

# Install necessary libraries
!pip install ultralytics roboflow pyyaml --quiet

# Verify GPU availability
import torch
print(f"PyTorch version: {torch.__version__}")
print(f"GPU available: {torch.cuda.is_is_available()}")
if torch.cuda.is_available():
    print(f"GPU name: {torch.cuda.get_device_name(0)}")
else:
    print("Warning: No GPU found. Training will be slow. Go to Runtime > Change runtime type > T4 GPU.")

"""## 2. Dataset Download and Management

This section handles downloading the Braille dataset from Roboflow. If you are running this notebook locally and already have the dataset, you can skip the download step and provide the local path.

**For Roboflow Download:**
To securely use your Roboflow API key, it's recommended to store it in Colab's Secrets Manager. Click the "🔑" icon on the left panel, add a new secret named `ROBOFLOW_API_KEY`, and paste your key there.

"""

# Commented out IPython magic to ensure Python compatibility.
from roboflow import Roboflow
from google.colab import userdata
import os

# --- Configuration for Dataset --- #
# Set `LOCAL_DATASET_PATH` if you have the dataset downloaded locally.
# Example: LOCAL_DATASET_PATH = './my_braille_dataset'
LOCAL_DATASET_PATH = None  # Set to your local path or leave None to download from Roboflow

ROBOFLOW_API_KEY = userdata.get('ROBOFLOW_API_KEY') # Get API key from Colab Secrets
ROBOFLOW_WORKSPACE = "braille-jjezl"
ROBOFLOW_PROJECT = "braille-detection-v2-xpwue"
ROBOFLOW_VERSION = 1
DATASET_FORMAT = "yolov8"
DATASET_LOCATION = "./dataset"

# --- Download or Load Dataset --- #
if LOCAL_DATASET_PATH:
    print(f"Using local dataset from: {LOCAL_DATASET_PATH}")
    dataset_path = LOCAL_DATASET_PATH
else:
    if not ROBOFLOW_API_KEY:
        raise ValueError("ROBOFLOW_API_KEY not found. Please set it in Colab Secrets or provide a LOCAL_DATASET_PATH.")

    print("Attempting to download dataset from Roboflow...")
    try:
        rf = Roboflow(api_key=ROBOFLOW_API_KEY)
        project = rf.workspace(ROBOFLOW_WORKSPACE).project(ROBOFLOW_PROJECT)
        version = project.version(ROBOFLOW_VERSION)
        dataset = version.download(DATASET_FORMAT, location=DATASET_LOCATION)
        dataset_path = dataset.location
        print("✅ Dataset downloaded successfully!")
        print(f"📁 Downloaded to: {dataset_path}")
    except Exception as e:
        print(f"❌ Error downloading dataset from Roboflow: {e}")
        print("Please ensure your API key is correct and the project details are valid.")
        print("Alternatively, provide a LOCAL_DATASET_PATH.")
        raise

# Make dataset_path globally accessible for subsequent cells
# This will be used in data.yaml path fixing and training
# %store dataset_path

# Check what we downloaded or loaded
import os
import yaml

# Ensure dataset_path is defined, either from download or local path
if 'dataset_path' not in locals() and 'dataset_path' not in globals():
    print("Error: Dataset path not set. Please run the previous cell.")
else:
    print(f"📊 Dataset Summary from: {dataset_path}")

    # Count images (robustly handle missing directories)
    train_imgs = len(os.listdir(f"{dataset_path}/train/images")) if os.path.exists(f"{dataset_path}/train/images") else 0
    val_imgs   = len(os.listdir(f"{dataset_path}/valid/images")) if os.path.exists(f"{dataset_path}/valid/images") else 0
    test_imgs  = len(os.listdir(f"{dataset_path}/test/images"))  if os.path.exists(f"{dataset_path}/test/images")  else 0

    print(f"   Train images : {train_imgs}")
    print(f"   Val images   : {val_imgs}")
    print(f"   Test images  : {test_imgs}")
    print(f"   Total        : {train_imgs + val_imgs + test_imgs}")

    # Show data.yaml contents
    yaml_path = f"{dataset_path}/data.yaml"
    if os.path.exists(yaml_path):
        print("\n📄 data.yaml contents:")
        with open(yaml_path, 'r') as f:
            print(f.read())
    else:
        print(f"Warning: data.yaml not found at {yaml_path}")

# Fix data.yaml paths to absolute paths (important for Colab)
import yaml
import os

yaml_path = "./dataset/data.yaml"
abs_dataset = os.path.abspath("./dataset")

with open(yaml_path, 'r') as f:
    data = yaml.safe_load(f)

# Update paths to absolute
data['train'] = f"{abs_dataset}/train/images"
data['val']   = f"{abs_dataset}/valid/images"
if 'test' in data:
    data['test'] = f"{abs_dataset}/test/images"

with open(yaml_path, 'w') as f:
    yaml.dump(data, f)

print("✅ data.yaml paths fixed!")
print(f"   Train: {data['train']}")
print(f"   Val:   {data['val']}")
print(f"   Classes: {data.get('names', 'N/A')}")

"""## Step 3 — Preview Sample Images"""

import cv2
import matplotlib.pyplot as plt
import glob
import random

# Show 6 random training images
train_images = glob.glob("./dataset/train/images/*")
sample = random.sample(train_images, min(6, len(train_images)))

fig, axes = plt.subplots(2, 3, figsize=(15, 8))
axes = axes.flatten()

for i, img_path in enumerate(sample):
    img = cv2.imread(img_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    axes[i].imshow(img)
    axes[i].set_title(os.path.basename(img_path), fontsize=9)
    axes[i].axis('off')

plt.suptitle('Sample Training Images', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('sample_training_images.png', dpi=100, bbox_inches='tight')
plt.show()
print("✅ Sample images displayed")

"""## Step 4 — Train YOLOv8

We use **YOLOv8n** (nano) — fastest model, good accuracy, runs in real-time on CPU.

| Model | Speed (CPU) | Accuracy | Best For |
|---|---|---|---|
| yolov8n | ~45ms | Good | ✅ Hackathon (real-time) |
| yolov8s | ~90ms | Better | If you have time |
| yolov8m | ~200ms | Best | Not real-time on CPU |

"""

from ultralytics import YOLO

# Load YOLOv8 nano — pretrained on COCO (transfer learning)
model = YOLO('yolov8n.pt')

print("✅ YOLOv8n loaded — starting training...")
print("⏱️  Expected time: 45–90 mins on T4 GPU")
print("📊 Watch the mAP50 column — aim for > 0.75")
print("-" * 60)

# ============================================================
# TRAIN THE MODEL
# ============================================================
results = model.train(
    data       = os.path.abspath('./dataset/data.yaml'),
    epochs     = 80,          # 80 epochs — good balance for hackathon time
    imgsz      = 640,         # standard YOLO input size
    batch      = 16,          # T4 GPU can handle 16
    patience   = 20,          # early stopping if no improvement
    optimizer  = 'AdamW',
    lr0        = 0.001,       # initial learning rate
    lrf        = 0.01,        # final lr = lr0 * lrf
    momentum   = 0.937,
    weight_decay = 0.0005,
    warmup_epochs = 3,
    mosaic     = 1.0,         # data augmentation
    flipud     = 0.0,         # don't flip vertically (Braille orientation matters)
    fliplr     = 0.5,         # horizontal flip OK
    degrees    = 5.0,         # small rotation
    translate  = 0.1,
    scale      = 0.5,
    hsv_h      = 0.015,
    hsv_s      = 0.3,         # color augmentation
    hsv_v      = 0.4,         # brightness variation (critical for embossed Braille)
    name       = 'braillevision',
    project    = 'runs/detect',
    exist_ok   = True,
    device     = 0 if torch.cuda.is_available() else 'cpu',
    verbose    = True,
)

print("\n🎉 Training complete!")

"""## Step 5 — Evaluate Model Performance"""

# Load best weights and evaluate on validation set
best_model = YOLO('/content/runs/detect/runs/detect/braillevision/weights/best.pt')
metrics = best_model.val(data=os.path.abspath('./dataset/data.yaml'))

print("\n📊 FINAL MODEL METRICS")
print("=" * 40)
print(f"mAP@0.50       : {metrics.box.map50:.4f}")
print(f"mAP@0.50:0.95  : {metrics.box.map:.4f}")
print(f"Precision      : {metrics.box.mp:.4f}")
print(f"Recall         : {metrics.box.mr:.4f}")
print("=" * 40)

if metrics.box.map50 >= 0.75:
    print("✅ EXCELLENT — Model is ready for deployment!")
elif metrics.box.map50 >= 0.60:
    print("✅ GOOD — Model works well, can improve with more data")
elif metrics.box.map50 >= 0.45:
    print("⚠️  FAIR — Try adding your own Braille photos")
else:
    print("❌ LOW — Check dataset quality, try more epochs")

# Show training curves (loss, mAP over epochs)
from IPython.display import Image as IPImage

results_png = 'runs/detect/braillevision/results.png'
if os.path.exists(results_png):
    display(IPImage(results_png, width=900))
    print("📈 Training curves shown above")

# Show confusion matrix
confusion_png = 'runs/detect/braillevision/confusion_matrix.png'
if os.path.exists(confusion_png):
    display(IPImage(confusion_png, width=600))
    print("📊 Confusion matrix shown above")

"""## Step 6 — Test on Sample Images"""

import cv2
import matplotlib.pyplot as plt
import glob
import random

# Test on 4 validation images
val_images = glob.glob('./dataset/valid/images/*')[:4]

fig, axes = plt.subplots(1, len(val_images), figsize=(20, 5))
if len(val_images) == 1:
    axes = [axes]

for i, img_path in enumerate(val_images):
    result = best_model(img_path, conf=0.4, verbose=False)[0]
    annotated = result.plot()
    annotated_rgb = cv2.cvtColor(annotated, cv2.COLOR_BGR2RGB)

    axes[i].imshow(annotated_rgb)
    axes[i].set_title(f"Detections: {len(result.boxes)}", fontsize=11)
    axes[i].axis('off')

plt.suptitle('🔵 BrailleVision — Sample Detections', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('sample_detections.png', dpi=120, bbox_inches='tight')
plt.show()
print("✅ Detection results shown above")

"""## Step 7 — Test on YOUR Braille Photo
Upload your own Braille paper photo and test it here!
"""

from google.colab import files

print("📸 Upload your own Braille paper photo now...")
uploaded = files.upload()

for filename in uploaded:
    result = best_model(filename, conf=0.35, verbose=False)[0]
    annotated = result.plot()
    annotated_rgb = cv2.cvtColor(annotated, cv2.COLOR_BGR2RGB)

    plt.figure(figsize=(12, 8))
    plt.imshow(annotated_rgb)
    plt.title(f"Your Braille | Dots detected: {len(result.boxes)}",
              fontsize=14, fontweight='bold')
    plt.axis('off')
    plt.savefig(f'my_braille_result_{filename}', dpi=120, bbox_inches='tight')
    plt.show()

    print(f"\n📊 Results for {filename}:")
    for box in result.boxes:
        conf = float(box.conf[0])
        print(f"   Dot detected — confidence: {conf:.2%}")

"""## Step 7.1 — Improve the Model (Optional)

If your model's performance (mAP50) is not satisfactory, here are some common strategies to improve it:

1.  **More Data / Data Augmentation:** This is often the most effective method. Consider gathering more diverse Braille images or applying more aggressive augmentation techniques during training.
2.  **Longer Training:** Increase the number of `epochs`. The current 80 epochs is good for a hackathon, but more complex datasets might benefit from 200-300 epochs.
3.  **Different Model Size:** Try `yolov8s.pt` (small) or `yolov8m.pt` (medium). These are larger models and can capture more complex features, but they will take longer to train and require more memory.
4.  **Hyperparameter Tuning:** Adjust `lr0`, `lrf`, `batch`, and other parameters. Ultralytics provides tools for this, but it can be time-consuming.

Let's try training with a `yolov8s` model and more epochs as an example.
"""

from ultralytics import YOLO
import os
import torch

# Load YOLOv8 small — pretrained on COCO (transfer learning)
# You could also try 'yolov8m.pt' for an even larger model
model_improved = YOLO('yolov8s.pt')

print("✅ YOLOv8s loaded — starting improved training...")
print("⏱️  Expected time: 90–180 mins on T4 GPU (for 150 epochs)")
print("📊 Watch the mAP50 column — aim for > 0.75")
print("-" * 60)

# ============================================================
# TRAIN THE MODEL WITH IMPROVED PARAMETERS
# ============================================================
results_improved = model_improved.train(
    data       = os.path.abspath('./dataset/data.yaml'),
    epochs     = 150,         # Increased epochs
    imgsz      = 640,         # standard YOLO input size
    batch      = 16,          # T4 GPU can handle 16
    patience   = 30,          # Increased early stopping patience
    optimizer  = 'AdamW',
    lr0        = 0.001,       # initial learning rate
    lrf        = 0.01,        # final lr = lr0 * lrf
    momentum   = 0.937,
    weight_decay = 0.0005,
    warmup_epochs = 3,
    mosaic     = 1.0,         # data augmentation
    flipud     = 0.0,         # don't flip vertically (Braille orientation matters)
    fliplr     = 0.5,         # horizontal flip OK
    degrees    = 5.0,         # small rotation
    translate  = 0.1,
    scale      = 0.5,
    hsv_h      = 0.015,
    hsv_s      = 0.3,         # color augmentation
    hsv_v      = 0.4,         # brightness variation (critical for embossed Braille)
    name       = 'braillevision_improved', # New run name
    project    = 'runs/detect', # Project directory remains the same
    exist_ok   = True,
    device     = 0 if torch.cuda.is_available() else 'cpu',
    verbose    = True,
)

print("\n🎉 Improved training complete!")

"""After running the improved training, you would then re-evaluate the model performance, visualize new training curves, and re-test on sample images using the `best.pt` from the `braillevision_improved` run.

## Step 8 — Save & Download Model Weights
Download `best.pt` — this is what goes in your GitHub repo under `model/`
"""

import shutil

# Copy weights to root for easy download
shutil.copy('/content/runs/detect/runs/detect/braillevision/weights/best.pt', 'best.pt')
shutil.copy('/content/runs/detect/runs/detect/braillevision/weights/last.pt', 'last.pt')

# Also copy results
shutil.copy('/content/runs/detect/runs/detect/braillevision/results.csv', 'training_results.png')

print("✅ Files ready for download:")
print("   best.pt              ← Use this in your project")
print("   last.pt              ← Last checkpoint")
print("   training_results.png ← Include in GitHub repo")

# Download them
from google.colab import files
files.download('best.pt')
files.download('training_results.png')

"""## Step 9 — Export model_info.md for GitHub
This goes into `model/model_info.md` in your repo.
"""

import datetime

map50   = metrics.box.map50
map5095 = metrics.box.map
prec    = metrics.box.mp
rec     = metrics.box.mr
nc      = data.get('nc', 1)
names   = data.get('names', ['dot'])

model_info = f"""# BrailleVision Model Info

## Architecture
- **Model:** YOLOv8n (nano)
- **Framework:** Ultralytics YOLOv8
- **Task:** Object Detection (Braille dot detection)
- **Input Size:** 640×640
- **Classes:** {nc} — {names}
- **Pretrained Base:** yolov8n.pt (COCO)

## Training Details
- **Dataset:** Braille Detection (Roboflow Universe)
- **Epochs:** 80 (with early stopping, patience=20)
- **Batch Size:** 16
- **Optimizer:** AdamW
- **Learning Rate:** 0.001 → 0.00001
- **Augmentations:** Mosaic, HSV jitter, flip, scale, translate
- **Hardware:** Google Colab T4 GPU
- **Trained On:** {datetime.datetime.now().strftime('%Y-%m-%d')}

## Performance (Validation Set)
| Metric | Value |
|---|---|
| mAP@0.50 | {map50:.4f} |
| mAP@0.50:0.95 | {map5095:.4f} |
| Precision | {prec:.4f} |
| Recall | {rec:.4f} |

## Files
- `best.pt` — Best checkpoint (use this for inference)
- `last.pt` — Final epoch checkpoint

## Inference
```python
from ultralytics import YOLO
model = YOLO('model/best.pt')
results = model('your_braille_image.jpg', conf=0.4)
```

## Judge Verification
Model weights hosted at: [ADD YOUR GOOGLE DRIVE LINK HERE]
"""

with open('model_info.md', 'w') as f:
    f.write(model_info)

print(model_info)
files.download('model_info.md')

"""## Step 10 — Upload best.pt to Google Drive (for judge access)
Required by hackathon submission rules — judges must be able to verify the model.
"""

from google.colab import drive
drive.mount('/content/drive')

import shutil
import os

# Create folder in Drive
drive_folder = '/content/drive/MyDrive/BrailleVision_Model'
os.makedirs(drive_folder, exist_ok=True)

# Copy files
shutil.copy('best.pt',              f'{drive_folder}/best.pt')
shutil.copy('last.pt',              f'{drive_folder}/last.pt')
shutil.copy('training_results.png', f'{drive_folder}/training_results.png')
shutil.copy('model_info.md',        f'{drive_folder}/model_info.md')
shutil.copy('./dataset/data.yaml',  f'{drive_folder}/data.yaml')

print("✅ All files saved to Google Drive!")
print(f"📁 Folder: {drive_folder}")
print("")
print("📋 Next steps:")
print("1. Go to drive.google.com")
print("2. Find the BrailleVision_Model folder")
print("3. Right-click → Share → Anyone with link can view")
print("4. Copy that link and paste it into your GitHub repo's model/model_info.md")

"""## ✅ Summary — What You Have Now

| File | Purpose | Where to put it |
|---|---|---|
| `best.pt` | Trained model weights | `model/best.pt` in GitHub |
| `last.pt` | Last checkpoint | `model/last.pt` in GitHub |
| `training_results.png` | Loss + mAP curves | `training/results/` in GitHub |
| `model_info.md` | Model documentation | `model/model_info.md` in GitHub |
| Google Drive link | Judge verification | In README + submission form |

### 🎯 How to use best.pt in your project:
```python
from ultralytics import YOLO
model = YOLO('model/best.pt')           # load
results = model('braille_image.jpg')    # infer
boxes = results[0].boxes.xyxy           # get dot bounding boxes
```

### 📝 Training command (for your GitHub yolo_train_command.txt):
```
yolo detect train data=dataset/data.yaml model=yolov8n.pt epochs=80 imgsz=640 batch=16 name=braillevision
```

---
**BrailleVision Hackathon 2026 — Good luck! 🔵**
